#+TITLE: PHP SdICoop - Client

A PHP package for connecting to [[https://www.fatturapa.gov.it/export/fatturazione/en/sdi.htm?l=en][Italian Exchange System (aka "SdI")]] web services.

Please refer to
- [[https://github.com/taocomp/php-sdicoop-server][PHP SdICoop - Server]] to implement your web services required by SdI
- [[https://github.com/taocomp/php-e-invoice-it][PHP E-invoice It]] for managing italian e-invoice and notice XML formats

See [[https://forum.italia.it/c/fattura-pa][Forum Italia - Fatturazione Elettronica]] for server configuration, interoperability tests, etc. In particular:
- Apache configuration :: [[https://forum.italia.it/t/accreditamento-sdicoop-configurazione-ssl-su-apache/3314][Accreditamento SDICoop: configurazione SSL su Apache - Fatturazione Elettroni...]]
- Interoperability tests :: [[https://forum.italia.it/t/test-interoperabilita-soluzioni/4370][Test Interoperabilità Soluzioni - Fatturazione Elettronica - Forum Italia]]

If you need a "ready to start" solution, or a consultancy for your PHP project, please feel free to contact us at [[mailto:e-invoicing@taocomp.com][e-invoicing@taocomp.com]].

* Getting started
** Dependencies
- ~php-curl~
- ~php-soap~

Compatible with PHP 5.5+.

** Send invoices to SdI (web service "SdIRiceviFile", endpoint test)
Setup client:
#+BEGIN_SRC 
    $client = new TestSdiRiceviFile(array(
        'key'     => __DIR__ . '/../assets/key/client.key',
        'cert'    => __DIR__ . '/../assets/certs/client.pem',
        'ca_cert' => __DIR__ . '/../assets/certs/ca.pem'
    ));
#+END_SRC

or:

#+BEGIN_SRC 
    // Set certs and key
    Client::setPrivateKey('/path/to/client.key');
    Client::setClientCert('/path/to/client.pem');
    Client::setCaCert('/path/to/ca.pem');

    $client = new TestSdiRiceviFile();
#+END_SRC

or (for PHP 5.5+):

#+BEGIN_SRC 
    // Set certs and key
    Client::setPrivateKey(__DIR__ . '/client.key');
    Client::setClientCert(__DIR__ . '/client.pem');
    Client::setCaCert(__DIR__ . '/ca.pem');

    $client = new Client(array(
        'endpoint' => 'https://testservizi.fatturapa.it/ricevi_file',
        'wsdl'     => __DIR__ . '/../wsdl/SdIRiceviFile_v1.0.wsdl'
    ));
#+END_SRC

Send invoice:
#+BEGIN_SRC 
    $fileSdI = new FileSdIBase();
    $fileSdI->load(__DIR__ . '/invoice.xml');
    $response = new RispostaSdIRiceviFile($client->RiceviFile($fileSdI));

    // Process response:
    // -----------------------------------------
    // $id       = $response->IdentificativoSdI;
    // $datetime = $response->DataOraRicezione;
    // $error    = $response->Errore;
    // -----------------------------------------
#+END_SRC

You can also send ~\Taocomp\Einvoicing\FatturaElettronica~ objects: see [[https://github.com/taocomp/php-e-invoice-it][https://github.com/taocomp/php-e-invoice-it]].

** Send notices to SdI (web service "SdIRiceviNotifica", endpoint test)
Setup client:
#+BEGIN_SRC 
    $client = new TestSdiRiceviNotifica(array(
        'key'     => __DIR__ . '/../assets/key/client.key',
        'cert'    => __DIR__ . '/../assets/certs/client.pem',
        'ca_cert' => __DIR__ . '/../assets/certs/ca.pem'
    ));
#+END_SRC

(see "Send invoices" for different client instantiations).

Send notice:
#+BEGIN_SRC 
    $fileSdI = new FileSdI();
    $fileSdI->load(__DIR__ . '/notice.xml');
    $response = new RispostaSdINotificaEsito($client->NotificaEsito($fileSdI));

    // Process response:
    // ----------------------------------
    // $result          = $response->Esito;
    // $discard         = $response->ScartoEsito;
    // $discardFilename = $discard->NomeFile;
    // $discardFile     = $discard->File;
    // ----------------------------------
#+END_SRC

You can also send ~\Taocomp\Einvoicing\EsitoCommittente~ objects: see [[https://github.com/taocomp/php-e-invoice-it][https://github.com/taocomp/php-e-invoice-it]].

* Credits
We want to thank all contributors of [[https://forum.italia.it/c/fattura-pa][Forum Italia - Fatturazione Elettronica]] who have shared their snippets and any available info.

Thanks to Luca Cristofalo for testing the code on his old PHP 5.5.38. :-)

* License
GPLv3.
